module.exports = {
    MONGO_DB_URL: process.env.MONGO_DB_URL,
    INCENTIVE_MANAGER_CONTRACT_ADDRESS: process.env.INCENTIVE_MANAGER_CONTRACT_ADDRESS,
    ALCHAMY_RPC_URL: process.env.ALCHAMY_RPC_URL,
    ADMIN_PRIVATE_KEY: process.env.ADMIN_PRIVATE_KEY,
    FOLLOWER_CONSTANT : process.env.FOLLOWER_CONSTANT,
    POST_CONSTANT : process.env.POST_CONSTANT
}